service: plant-monitoring-movie

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  timeout: 180
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}
            - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - '*'

functions:
  create:
    handler: handler.lambda_handler
    events:
      - schedule: cron(50 9 * * ? *) # JST 19:50 (UTC 10:50) daily

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []